name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: CI
    services:
      cosmwasm-etl-db:
        image: postgres
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: appPW
          POSTGRES_DB: cosmwasm_etl
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Run Golang linter
      uses: golangci/golangci-lint-action@v8

    - name: Tests
      shell: bash
      run: |
        echo "${{ secrets.CONFIG }}" > config.yaml
        make test

    - name: Migration Tests
      run: |
        make parser-migrate-up
        make parser-migrate-test
        make parser-migrate-down
      # Add if more needed

    - name: Build all
      run: make build-all
