name: Publish

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_ID: cosmwasm-etl
  GCP_GAR_REPOSITORY: ${{ vars.GCP_GAR_REPOSITORY }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
  GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: build and package image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check if tag commit is on main branch
        id: check_branch
        run: |
          branches_containing_tag=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
          echo "Branches containing tag: $branches_containing_tag"

          if echo "$branches_containing_tag" | grep -Eq "^(origin/)?main"; then
            # get version from tag
            GIT_TAG=$(echo "${{ github.ref }}" | sed 's|refs/tags/v||')
            echo "tag=$GIT_TAG" >> $GITHUB_OUTPUT
          else
            echo "The tag commit is NOT on main branch. Exiting."
            exit 1
          fi

      - name: Build and save image
        id: build-images
        working-directory: .
        env:
          IMAGE_TAG: ${{ steps.check_branch.outputs.tag }}
        run: |
          for app_type in collector parser-dex aggregator; do
            echo "Building for $app_type"
            APP_PATH=$(echo $app_type | tr '-' '/')
            docker build --build-arg APP_PATH=$APP_PATH --build-arg VERSION=${IMAGE_TAG} --no-cache -t ${{ env.PROJECT_ID }}/$app_type:${IMAGE_TAG} .
            docker save -o ${{ runner.temp }}/${{ env.PROJECT_ID }}-$app_type.tar ${{ env.PROJECT_ID }}/$app_type:${IMAGE_TAG}
          done

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # ratchet:actions/upload-artifact@v7
        with:
          name: docker-images
          path: ${{ runner.temp }}/${{ env.PROJECT_ID }}-*.tar

  push_to_gar:
    name: Push images to Google Artifact Registry
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # ratchet:google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # ratchet:google-github-actions/setup-gcloud@v3

      - name: Authenticate to Repo
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # ratchet:actions/download-artifact@v8
        with:
          name: docker-images
          path: ${{ runner.temp }}

      - name: Load, tag and push image to GAR
        env:
          IMAGE_TAG: ${{ needs.build.outputs.tag }}
        run: |
          # Load all saved Docker images
          for tar in ${{ runner.temp }}/${{ env.PROJECT_ID }}-*.tar; do
            docker load -i "$tar"
          done

          for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep ^${{ env.PROJECT_ID }}); do
            IFS=':' read -r image_name tag <<< "$image"
            image_name=${image_name//\//-}
            docker tag $image $GCP_GAR_REPOSITORY/$image_name:$tag
            docker push $GCP_GAR_REPOSITORY/$image_name:$tag
          done
