name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    permissions:
      contents: write
      pull-requests: read
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@3d96a18cc4ec17e9dc69ddcc424ccafaf1f78ce2 # ratchet:orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --current --strip all
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # ratchet:softprops/action-gh-release@v3
        with:
          body_path: CHANGELOG.md
          tag_name: ${{ github.ref_name }}
